# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-10 00:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='Genre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('band', models.CharField(max_length=100)),
                ('youtube', models.URLField(blank=True)),
                ('soundcloud', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('minprice', models.PositiveIntegerField()),
                ('maxprice', models.PositiveIntegerField()),
                ('bandgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcoming.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Literally ANYTHING')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcoming.Venue'),
        ),
    ]
