# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-15 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'managed': False},
        ),
    ]
