# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
