# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-22 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0002_auto_20180314_2145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='show',
            table='upcoming_show',
        ),
    ]
