# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0002_events_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('band', models.CharField(max_length=100)),
                ('bandgenre', models.CharField(max_length=50)),
                ('youtube', models.URLField()),
                ('soundcloud', models.URLField()),
                ('spotify', models.URLField()),
                ('venue', models.CharField(max_length=100)),
                ('minprice', models.PositiveIntegerField()),
                ('maxprice', models.PositiveIntegerField()),
            ],
        ),
    ]
