# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-05 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0004_auto_20171105_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
    ]
