# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-05 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0006_venue_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='body',
            new_name='description',
        ),
    ]
