# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0007_auto_20171105_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='soundcloud',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='spotify',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
