# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 01:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
