# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170227_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='listimage',
            field=models.ImageField(default='D:\\DistortionDC\\distortiondc\x08log\\media\\default.jpg', upload_to='bloglistimages'),
        ),
    ]
