# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170308_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cheese',
            field=models.TextField(default='Line to go under title on main page, max 50 words, NO HTML HERE!'),
        ),
    ]
