# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170308_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='listimage',
            field=models.ImageField(default='bloglistimages/default.jpg', upload_to='bloglistimages/'),
        ),
    ]
