# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 17:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170729_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
